---

- include_role:
    name: 'ansible-role-pkg'
  vars:
    pkg_list: "{{ _consul_pkgs }}"

- name: 'delete the version file if requested'
  file:
    path: "{{ consul_artifact_version_flag_path }}"
    state: 'absent'
  when: consul_artifact_force_update

- name: 'check if the version file exists'
  stat:
    path: "{{ consul_artifact_version_flag_path }}"
  register: __consul_version_file_check_result

- name: 'get the current installed version'
  slurp:
    src: "{{ consul_artifact_version_flag_path }}"
  register: __consul_version_version_read_result
  when: __consul_version_file_check_result.stat.exists

- name: 'activate update'
  set_fact:
    __consul_do_update: True
  when: >
    (__consul_version_version_read_result.content is not defined)
    or
    (__consul_version_version_read_result.content is defined
      and __consul_version_version_read_result.content | b64decode != consul_artifact_version)

- name: 'unactivate update'
  set_fact:
    __consul_do_update: False
  when: >
    __consul_version_version_read_result.content is defined
    and __consul_version_version_read_result.content | b64decode == consul_artifact_version

- block:
    - include_role:
        name: 'ansible-role-verify_artifact'
      vars:
        verify_artifact_tmpdir: "{{ consul_artifact_tmpdir }}"
        verify_artifact_pgp_key: "{{ consul_pgp_key }}"
        verify_artifact_sum_url: "{{ consul_artifact_sum_url }}"
        verify_artifact_signature_url: "{{ consul_artifact_signature_url }}"
        verify_artifact_download_url: "{{ consul_artifact_url }}"
        verify_artifact_cksum_algo: "{{ consul_artifact_sum_algo }}"

    - name: 'unarchive archive in the temporary directory'
      unarchive:
        src: "{{ consul_artifact_tmpdir }}/{{ consul_artifact_url | basename }}"
        dest: "{{ consul_artifact_tmpdir }}"
        owner: 'root'
        group: 'root'
        mode: '0700'
        remote_src: True

    - name: 'install the binaries'
      copy:
        src: "{{ consul_artifact_tmpdir }}/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: 'root'
        group: 'root'
        mode: '0755'
        remote_src: True
      loop:
        - src: 'consul'
          dest: '/usr/sbin/consul'
      notify:
        - 'consul_restart_handler'

    - name: 'write the version file'
      copy:
        content: "{{ consul_artifact_version }}"
        dest: "{{ consul_artifact_version_flag_path }}"
        owner: 'root'
        group: 'root'
        mode: '0644'

  always:
    - name: 'delete tmpdir'
      file:
        path: "{{ consul_artifact_tmpdir }}"
        state: 'absent'

  when: __consul_do_update
