---

- name: 'create group'
  group:
    name: "{{ _consul_group }}"
    gid: "{{ _consul_groupid | default(omit) }}"
    system: True

- name: 'create user'
  user:
    name: "{{ _consul_user }}"
    group: "{{ _consul_group }}"
    home: '/nonexistent'
    create_home: False
    shell: '/bin/false'
    uid: "{{ _consul_userid | default(omit) }}"
    system: True

- name: 'create directories'
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: 'directory'
  loop:
    - path: "{{ _consul_conf_dir }}"
      owner: 'root'
      group: "{{ _consul_group }}"
      mode: "0750"

    - path: "{{ _consul_data_dir }}"
      owner: "{{ _consul_user }}"
      group: "{{ _consul_group }}"
      mode: "0750"
